// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PollTestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void pollTest() {
    driver.Navigate().GoToUrl("https://gimnasia.volozhin-edu.gov.by/");
    driver.Manage().Window.Size = new System.Drawing.Size(1488, 878);
    js.ExecuteScript("window.scrollTo(0,1689.5999755859375)");
    driver.FindElement(By.CssSelector("a:nth-child(5) > img")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".goog-te-combo"));
      dropdown.FindElement(By.XPath("//option[. = 'русский']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.CssSelector(".goog-te-combo"));
      dropdown.FindElement(By.XPath("//option[. = 'Выбрать язык']")).Click();
    }
    driver.FindElement(By.CssSelector("label:nth-child(4)")).Click();
    driver.FindElement(By.CssSelector(".VoteSubmitButton")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Спасибо за высказанное мнение!"));
    driver.FindElement(By.LinkText("Результаты опросов")).Click();
    driver.FindElement(By.CssSelector("g:nth-child(4) > path:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector("path:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector("g:nth-child(6) > path:nth-child(2)")).Click();
  }
}
